package com.example.employeeShiftScheduling.model

import ai.timefold.solver.core.api.domain.solution.PlanningEntityCollectionProperty
import ai.timefold.solver.core.api.domain.solution.PlanningScore
import ai.timefold.solver.core.api.domain.solution.PlanningSolution
import ai.timefold.solver.core.api.domain.valuerange.ValueRangeProvider
import ai.timefold.solver.core.api.score.buildin.hardsoft.HardSoftScore


//The annotation is applied to the ShiftSchedule class to indicate to Timefold that it is a part of the planning problem and can be used as input and output. It signifies the eligibility of this
// class to be solved by Timefold.
@PlanningSolution
class ShiftSchedule {

    // employees field provides a list of available employees using @ValueRangeProvider annotation. It represents individuals available for shifts.
    @ValueRangeProvider(id = "employees")
    var employee:List<Employee>?=null

    // The shifts field provides a list of all shifts using the @PlanningEntityCollectionProperty annotation. Each shift is associated with a specific date, start time, end time, and required skill.
    // When input data is provided to the ShiftSchedule class, the Timefold algorithm analyzes this data and utilizes it to generate a feasible solution.
    @PlanningEntityCollectionProperty
    var shifts:List<Shift>?=null


    // The score field in ShiftSchedule class, annotated with @PlanningScore, evaluates solution quality, indicating its effectiveness and areas for improvement.
    @PlanningScore
    var score: HardSoftScore?= null


    constructor(){

    }
    constructor(employees: List<Employee>,shift: List<Shift>){
        this.employee= employees
        this.shifts = shift
    }
}


//output :-// The output of the ShiftSchedule class is the solution generated by the Timefold algorithm. It typically consists of two main components: 1. Assigned Employees: Each shift is assigned
// to an employee in the solution generated by the Timefold algorithm. These employees are the most suitable and available for the shifts.